### PR TITLE
Add httpplease plugin to set withCredentials = true on xhr requests.

### PR DESCRIPTION
**Pull request by ghost**
Cookies aren't currently set in ajax requests made by the webapp. This means that if private mirrors of the api with authentication turned on are sent to call a subdomain (e.g. api.targetvalidation.org), the cookies aren't sent, and the api rejects the request.

I haven't been able to test the consequence of this change in a situation where there isn't authentication set up on the api, so I don't know whether or not this will break the public build. If it wouldn't work, then I'll move it to use a config option to turn this on.

### CODE REVIEW

**Comment by ghost** [comment]
Have moved this to only include the new httpplease plugin if the user explicitly requests it using a method call on the api object.

**Comment by ghost** [comment]
@emepyc I think this is ready to merge, but would appreciate any comments.

**Comment by emepyc** [comment]
It looks good to me, but I haven't tried it.
Since I'm not in OT anymore I think @LucaFumis or @peatroot should take a look as well

**Comment by LucaFumis** [comment]
Hey Richard, sorry this was on my to-do list. Testing it now...

**Pull request merged**
